// Generated by CoffeeScript 1.6.3
module("Dropbox");

asyncTest("Auto Login(12s)", 1, function() {
  setTimeout(function() {
    if (!Nimbus.Auth.authorized()) {
      return Nimbus.Auth.authorize("Dropbox");
    }
  }, 8000);
  return setTimeout(function() {
    QUnit.start();
    equal(Nimbus.Auth.authorized(), true, "have  been  login");
    return window.Entry3 = Nimbus.Model.setup("Entry3", ["note", "comment"]);
  }, 9000);
});

asyncTest("Set Model and  Sync(12s)", 1, function() {
  setTimeout(function() {
    ok(Entry3, "Entry3  have been  setup");
    return Entry3.sync_all();
  }, 4000);
  return setTimeout(function() {
    return QUnit.start();
  }, 12000);
});

test("clear old objecgs (8s)", function() {
  var testCall;
  QUnit.stop();
  Entry3.destroyAll();
  testCall = function() {
    return Nimbus.Client.Dropbox.send_request('GET', 'https://api.dropbox.com/1/metadata/sandbox/unit_test/Entry3', '', function(data) {
      var ob;
      ob = data.contents.length;
      QUnit.equal(ob, 0, "Entry3 is empty now, will check later");
      return QUnit.start();
    });
  };
  return setTimeout(testCall, 8000);
});

test("add 5 objects", function() {
  var testCall;
  Entry3.create({
    "note": "note1",
    "comment": "comment1"
  });
  Entry3.create({
    "note": "note2",
    "comment": "comment2"
  });
  Entry3.create({
    "note": "note3",
    "comment": "comment3"
  });
  Entry3.create({
    "note": "note4",
    "comment": "comment4"
  });
  Entry3.create({
    "note": "note5",
    "comment": "comment5"
  });
  QUnit.stop();
  testCall = function() {
    return Nimbus.Client.Dropbox.send_request('GET', 'https://api.dropbox.com/1/metadata/sandbox/unit_test/Entry3', '', function(data) {
      var ob;
      ob = data.contents.length;
      QUnit.equal(ob, 5, "Entry3 have added 5 objects");
      return QUnit.start();
    });
  };
  return setTimeout(testCall, 10000);
});

test("delete an objects(5s)", function() {
  var a_id, aa, path, testCall, testCall2;
  aa = window.Entry3.findByAttribute("note", "note1");
  a_id = aa.id;
  QUnit.stop();
  path = "/unit_test/Entry3/" + a_id + ".txt";
  testCall = function() {
    return Nimbus.Client.Dropbox.getFileContents(path, function(data) {
      var ob;
      ob = data;
      QUnit.equal(ob.id, a_id, "find the item in gdrive");
      return aa.destroy();
    });
  };
  setTimeout(testCall, 5000);
  testCall2 = function() {
    return Nimbus.Client.Dropbox.send_request('GET', 'https://api.dropbox.com/1/metadata/sandbox/unit_test/Entry3', '', function(data) {
      var ob;
      ob = data.contents.length;
      QUnit.equal(ob, 4, "Entry3 is  4 objects  left now");
      return QUnit.start();
    });
  };
  setTimeout(testCall2, 10000);
});

asyncTest("Edit objects(5s)", 2, function() {
  var a_id, aaa, path, testCall, testCall2;
  aaa = window.Entry3.findByAttribute("note", "note2");
  a_id = aaa.id;
  path = "/unit_test/Entry3/" + a_id + ".txt";
  testCall = function() {
    return Nimbus.Client.Dropbox.getFileContents(path, function(data) {
      var ob;
      ob = data;
      QUnit.equal(ob.id, a_id, "find the item in gdrive");
      aaa.note = "note2222";
      return aaa.save();
    });
  };
  setTimeout(testCall, 3000);
  testCall2 = function() {
    return Nimbus.Client.Dropbox.getFileContents(path, function(data) {
      QUnit.start();
      QUnit.equal(data.note, "note2222", "find the item in gdrive");
      return Nimbus.Auth.logout();
    });
  };
  setTimeout(testCall2, 8000);
  return null;
});
