// Generated by CoffeeScript 1.6.3
(function() {
  (function() {
    var Nimbus, headID, newScript;
    if (window.Nimbus == null) {
      window.Nimbus = {};
    }
    Nimbus = window.Nimbus;
    window.handle_initialization = null;
    Nimbus.loaded = false;
    window.handleClientLoad = function() {
      console.log("loaded CALLED");
      Nimbus.loaded = true;
      if (Nimbus.gdrive_initialized) {
        return Nimbus.Auth.initialize();
      }
    };
    headID = document.getElementsByTagName("head")[0];
    newScript = document.createElement("script");
    newScript.type = "text/javascript";
    newScript.src = "https://apis.google.com/js/client.js?onload=handleClientLoad";
    return headID.appendChild(newScript);
  })();

}).call(this);
