// Generated by CoffeeScript 1.6.3
window.qunit_test_result = {};

window.qunit_test_count = {};

QUnit.log(function(details) {
  var item;
  console.log("Log: ", details.result, details.message);
  item = {};
  item.name = details.name;
  item.result = details.result;
  item.message = details.message;
  window.qunit_test_result[details.module] = window.qunit_test_result[details.module] || [];
  return window.qunit_test_result[details.module].push(item);
});

QUnit.moduleDone(function(details) {
  console.log("Finished running: ", details.name, "Failed/total: ", details.failed, details.total);
  window.qunit_test_count[details.name] = details;
  return window.qunit_test_is_done = true;
});

QUnit.done = function(results) {
  console.log('failed: ' + results.failed);
  console.log('passed: ' + results.passed);
  console.log('total: ' + results.total);
  return window.qunit_test_is_done = true;
};
