// Generated by CoffeeScript 1.6.3
(function() {
  var Dropbox;

  Dropbox = (function() {
    function Dropbox(options) {
      this.client = new DropboxClient(options);
    }

    return Dropbox;

  })();

}).call(this);
