// Generated by CoffeeScript 1.6.3
(function() {
  module("Local");

  test("check the data model inherited correctly", function() {
    return QUnit.equal(Entry.classname, "Nimbus.Model.LocalSync", "The class inherited correctly");
  });

  test("check the data is being saved to localstorage", function() {
    var localstorage_entry;
    Entry.destroyAll();
    Entry.create({
      "text": "one two three"
    });
    localstorage_entry = JSON.parse(localStorage["Entry"]);
    QUnit.equal(localstorage_entry[0].id, Entry.first().id, "The entry is there in localhost");
    return QUnit.equal(localstorage_entry[0].text, Entry.first().text, "The text is equal");
  });

}).call(this);
