// Generated by CoffeeScript 1.6.3
(function() {
  var Test, exports;

  window.debug = true;

  Nimbus.Auth.setup("GDrive", "424243246254-n6b2v8j4j09723ktif41ln247n75pnts.apps.googleusercontent.com", "https://www.googleapis.com/auth/drive", "unit_test");

  Test = Nimbus.Model.setup("test", ["at1", "at2"]);

  exports = this;

  exports.Test = Test;

}).call(this);
