// Generated by CoffeeScript 1.6.3
(function() {
  Nimbus.Auth.setup("Dropbox", "q5yx30gr8mcvq4f", "qy64qphr70lwui5", "unit_test");

  module("Dropbox Client Test");

  asyncTest("putFileContents", function() {
    expect(2);
    return Nimbus.Client.Dropbox.putFileContents(("/" + Nimbus.Auth.app_name) + "/test/test1.txt", "test one two three", function(resp) {
      log("resp", resp);
      start();
      console.log("putFileContents", resp);
      ok(resp.error == null, "no error exists");
      return ok(resp.path === '/unit_test/test/test1.txt', "putFileContents has the correct path");
    });
  });

  asyncTest("getFileContents", function() {
    expect(2);
    return Nimbus.Client.Dropbox.getFileContents(("/" + Nimbus.Auth.app_name) + "/test/test1.txt", function(resp) {
      log("resp", resp);
      start();
      console.log("getFileContents", resp);
      ok(resp.error == null, "no error exists");
      return ok(resp === "test one two three", "getFileContents correct content");
    });
  });

  asyncTest("getMetadataList", function() {
    expect(2);
    return Nimbus.Client.Dropbox.getMetadataList(("/" + Nimbus.Auth.app_name) + "/test/", function(resp) {
      log("resp", resp);
      start();
      console.log("metadata", resp);
      window.resp = resp;
      console.log("PATH", resp.contents[0].path);
      ok(resp.error == null, "no error exists");
      return ok(resp.contents[0].path === "/unit_test/test/test1.txt", "getMetadataList has the correct path");
    });
  });

  asyncTest("deletePath", function() {
    expect(2);
    return Nimbus.Client.Dropbox.deletePath(("/" + Nimbus.Auth.app_name) + "/test/test1.txt", function(resp) {
      log("resp", resp);
      start();
      console.log("deletePath", resp);
      ok(resp.error == null, "no error exists");
      return ok(resp.path === '/unit_test/test/test1.txt', "putFileContents has the correct path");
    });
  });

}).call(this);
