// Generated by CoffeeScript 1.6.3
(function() {
  window.Post = Nimbus.Model.setup("Post", ["title", "link", "category", "create_time"]);

  window.main = angular.module("main", []).controller("mainCtl", function($scope) {
    $scope.watchObject = Post.create({
      "title": "123",
      "link": "http://www.baidu.com"
    });
    return $scope.$watch("watchObject", function(n, v) {
      return console.log(JSON.stringify(n));
    });
  });

}).call(this);
