// Generated by CoffeeScript 1.6.3
var driver, webdriver;

webdriver = require('selenium-webdriver');

driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();

driver.get('http://localhost:8000');

driver.findElement(webdriver.By.name('Button1')).click();

driver.wait(function() {
  return driver.getTitle().then(function(title) {
    console.log(title);
    driver.findElement(webdriver.By.name("Email")).sendKeys("release@nimbusbase.com");
    driver.findElement(webdriver.By.name("Passwd")).sendKeys("freethecloud2013");
    return driver.findElement(webdriver.By.name("signIn")).click().then(function() {
      return driver.wait(function() {
        return driver.findElement(webdriver.By.id("submit_approve_access")).click();
      }, 10000).then(driver.wait(function() {
        return driver.findElement(webdriver.By.name('Start')).click();
      }, 4000));
    });
  });
}, 10000);
