// Generated by CoffeeScript 1.6.3
var add_update_file, driver, submit_approve_access, timeout, webdriver;

webdriver = require('selenium-webdriver');

driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();

driver.get('http://localhost:8000').then(function() {
  return driver.findElement(webdriver.By.name('Button1')).click().then(function() {
    return driver.getTitle().then(function(title) {
      console.log(title);
      driver.findElement(webdriver.By.name("Email")).sendKeys("release@nimbusbase.com");
      driver.findElement(webdriver.By.name("Passwd")).sendKeys("freethecloud2013");
      driver.findElement(webdriver.By.name("signIn")).click();
      return timeout(7000).then(submit_approve_access);
    });
  });
});

timeout = function(ms) {
  var d, start;
  d = webdriver.promise.defer();
  start = Date.now();
  setTimeout(function() {
    return d.fulfill(Date.now() - start);
  }, ms);
  return d.promise;
};

submit_approve_access = function(ms) {
  console.log('time: ' + ms + ' ms');
  driver.findElement(webdriver.By.id("submit_approve_access")).click();
  return timeout(5000).then(add_update_file);
};

add_update_file = function(ms) {
  console.log('time: ' + ms + ' ms');
  return driver.findElement(webdriver.By.id("file_upload")).sendKeys("/Users/Shared/nimbusbase_big.png");
};
