// Generated by CoffeeScript 1.6.3
var driver, printElapsed, timeout, webdriver;

webdriver = require('selenium-webdriver');

driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();

driver.get('http://localhost:8000');

driver.findElement(webdriver.By.name('Button2')).click();

timeout = function(ms) {
  var d, start;
  d = webdriver.promise.defer();
  start = Date.now();
  setTimeout(function() {
    return d.fulfill(Date.now() - start);
  }, ms);
  return d.promise;
};

printElapsed = function(ms) {
  return console.log('time: ' + ms + ' ms');
};

timeout(5000).then(function() {
  return console.log('click button');
});

timeout(20000).then(printElapsed);

timeout(25000).then(function(time) {
  printElapsed(time);
  return driver.getTitle().then(function(title) {
    console.log(title);
    driver.findElement(webdriver.By.id("login_email")).sendKeys("release@nimbusbase.com");
    return driver.findElement(webdriver.By.id("login_password")).sendKeys("freethecloud2013");
  }).then(function() {
    return driver.findElement(webdriver.By.id("login_submit")).click().then(function() {
      console.log('submited');
      return driver.findElement(webdriver.By.name("allow_access")).click();
    });
  }).then(function() {
    return driver.findElement(webdriver.By.id("file_upload")).sendKeys("/Users/Shared/nimbusbase_big.png");
  });
});
