// Generated by CoffeeScript 1.6.3
module("Dropbox Binary Test");

asyncTest("Auto Login(12s)", function() {
  return Nimbus.Auth.set_app_ready(function() {
    if (!Nimbus.Auth.authorized()) {
      Nimbus.Auth.authorize("Dropbox");
    }
    equal(Nimbus.Auth.authorized(), true, "have  been  login");
    start();
  });
});

asyncTest("Upload binary file(10s)", function() {
  var finput;
  finput = document.getElementById("file_upload");
  window.f1 = finput.files[0];
  return Nimbus.Binary.upload_file(window.f1, function(file) {
    window.f2 = file;
    return Nimbus.Client.Dropbox.getMetadataList("/" + window.f1.name, function(data) {
      deepEqual(1, 1, "have  been  added");
      return start();
    }, function(err) {
      deepEqual(0, 1, "have  been  added");
      return start();
    });
  });
});

test("delete this binary file(10s)", function() {
  stop();
  setTimeout(function() {
    Nimbus.Binary.delete_file(window.f2);
    return binary.find(window.f2.id).destroy();
  }, 5000);
  return setTimeout(function() {
    return Nimbus.Client.Dropbox.getMetadataList("/" + window.f1.name, function(data) {
      deepEqual(data.is_deleted, true, "have  been  deleted");
      return start();
    }, function(err) {
      deepEqual(0, 1, "have  been  deleted");
      return start();
    });
  }, 10000);
});
