// Generated by CoffeeScript 1.7.1
(function() {
  var sync_obj;

  sync_obj = {
    "GDrive": {
      "key": "281922744418.apps.googleusercontent.com",
      "scope": "https://www.googleapis.com/auth/drive",
      "app_name": "nimbus_todoList"
    },
    "Dropbox": {
      "key": "abgyfuygy8lh6xw",
      "secret": "kz4dqgty5b2p0km",
      "app_name": "nimbus_todoList"
    },
    "synchronous": true
  };

  Nimbus.Auth.setup(sync_obj);

}).call(this);
