// Generated by CoffeeScript 1.7.1
(function() {
  var todoApp;

  todoApp = angular.module('todoApp', []);

  todoApp.factory('isAuthorized', function() {
    var show, todoList;
    if ((window.todoList != null) && window.todoList !== "undefined") {
      todoList = window.todoList;
      show = todoList.authorized();
    } else {
      show = false;
    }
    alert("isAuthorized:" + show);
    return show;
  });

  todoApp.controller('LoginController', function($scope, isAuthorized) {
    var watchFn;
    $scope.show = isAuthorized;
    $scope.loginAction = function(model) {
      var todoList;
      todoList = window.todoList;
      switch (model) {
        case "Dropbox":
          todoList.authorize('Dropbox');
          break;
        case "GDrive":
          todoList.authorize('GDrive');
          break;
        default:
          console.error("loginAction request either Dropbox or GDrive only");
      }
      return todoList.authorized_callback(function() {
        return console.log("authorized!");
      });
    };
    watchFn = function() {
      if ($scope.show) {
        $('#loginView').animate({
          'opacity': '0.0'
        }, 500, 'linear', function() {
          $('#loginView').css({
            'display': 'none'
          });
          return $('#todoListView').css({
            'display': 'block'
          }).animate({
            'opacity': '1.0',
            'display': 'block'
          }, 500, 'linear');
        });
        return console.log("changed");
      }
    };
    return $scope.$watch('$scope.show', watchFn, true);
  });

  todoApp.controller('todoListViewController', function($scope) {
    return $scope.logout = function() {
      return window.todoList.logout();
    };
  });

}).call(this);
