// Generated by CoffeeScript 1.7.1
(function() {
  var todoApp;

  todoApp = angular.module('todoApp', []);

  todoApp.controller('todoListController', function($scope) {
    var Todos, init;
    Todos = [];
    $scope.todos = [];
    $scope.newTodo = "";
    init = function() {
      if (Nimbus.Auth.authorized()) {
        $('#loginView').animate({
          'opacity': '0.0'
        }, 1000, 'linear', function() {
          $('#loginView').css({
            'display': 'none'
          });
          return $('#todoListView').css({
            'display': 'block'
          }).animate({
            'opacity': '1.0',
            'display': 'block'
          }, 500, 'linear');
        });
        Todos = Nimbus.Model.setup('Todos', ['title', 'completed']);
        return Todos.sync_all(function() {
          var data, datas, _i, _len;
          datas = Todos.all();
          for (_i = 0, _len = datas.length; _i < _len; _i++) {
            data = datas[_i];
            $scope.todos.push(data);
          }
          return $scope.$apply();
        });
      }
    };
    Nimbus.Auth.app_ready_func = init;
    $scope.addNewTodo = function() {
      $scope.newTodo = $scope.newTodo.replace("/(^\s*)|(\s$)/g", "");
      if ($scope.newTodo.length) {
        alert($scope.newTodo);
        $scope.todos.push(Todos.create({
          "title": $scope.newTodo,
          "completed": false
        }));
        return $scope.newTodo = "";
      }
    };
    return $scope.logout = function() {
      Nimbus.Auth.logout();
      return window.location.reload();
    };
  });

}).call(this);
