// Generated by CoffeeScript 1.7.1
(function() {
  var todoList;

  todoList = function() {
    this.authorize = function(witch) {
      var sync_obj;
      sync_obj = {
        "GDrive": {
          "key": "281922744418.apps.googleusercontent.com",
          "scope": "https://www.googleapis.com/auth/drive",
          "app_name": "nimbus_todoList"
        },
        "Dropbox": {
          "key": "abgyfuygy8lh6xw",
          "secret": "kz4dqgty5b2p0km",
          "app_name": "nimbus_todoList"
        },
        "synchronous": true
      };
      Nimbus.Auth.setup(sync_obj);
      return Nimbus.Auth.authorize(witch);
    };
    this.authorized = function() {
      return Nimbus.Auth.authorized();
    };
    this.authorized_callback = function(callback) {
      if ((typeof callback) === "function") {
        return Nimbus.Auth.authorized_callback = callback;
      } else {
        return console.error("authorized argument request a function");
      }
    };
    this.logout = function() {
      Nimbus.Auth.logout();
      return window.location.reload();
    };
    this.release = function() {
      if ((window.todoList != null) && window.todoList !== "undefiend") {
        return window.todoList = null;
      }
    };
  };

  window.todoList = new todoList();

}).call(this);
