// Generated by CoffeeScript 1.6.3
(function() {
  var auth_obj, set_app_callback, sync_object;

  window.debug = true;

  sync_object = {
    GDrive: {
      key: "477192000959.apps.googleusercontent.com",
      scope: "https://www.googleapis.com/auth/drive",
      app_name: "chopsticks"
    },
    Dropbox: {
      key: "q5yx30gr8mcvq4f",
      secret: "qy64qphr70lwui5",
      app_name: "chopsticks"
    }
  };

  auth_obj = {
    GDrive_auth_button: "GDrive",
    Dropbox_auth_button: "Dropbox"
  };

  Nimbus.Auth.setup(sync_object);

  (function(auth_obj) {
    var auth_name, button_id, onclick, _results;
    onclick = function(name) {
      return function() {
        Nimbus.Auth.authorize(name);
        return false;
      };
    };
    _results = [];
    for (button_id in auth_obj) {
      auth_name = auth_obj[button_id];
      _results.push(document.getElementById(button_id).addEventListener("click", onclick(auth_name), false));
    }
    return _results;
  })(auth_obj);

  document.getElementById("log_out_button").addEventListener("click", function() {
    Nimbus.Auth.logout();
    document.getElementById("logout_block").classList.add('hidden');
    return document.getElementById("login_block").classList.remove('hidden');
  }, false);

  set_app_callback = function() {
    if (Nimbus.Auth.authorized()) {
      document.getElementById("login_block").classList.add('hidden');
      return document.getElementById("logout_block").classList.remove('hidden');
    }
  };

  Nimbus.Auth.set_app_ready(set_app_callback);

}).call(this);
