// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('Realtime', []);

  app.controller('realtimeController', function($scope) {
    var Docs, appReady, edit1, edit2;
    Docs = {};
    edit1 = document.getElementById('editer1');
    edit2 = document.getElementById('editer2');
    $scope.realtimeData = "Loading...";
    $scope.authorized = false;
    $scope.shared = false;
    $scope.isLoaded = false;
    $scope.realtimefile = {};
    $scope.femail = "";
    $scope.authorize = function() {
      var objAuth;
      objAuth = {
        "GDrive": {
          "key": "460727743836-sd4rpc7j65lr827sc5dokmmndhqhi48q.apps.googleusercontent.com",
          "scope": "https://www.googleapis.com/auth/drive",
          "app_name": "gdrive_realtime_test"
        },
        "Dropbox": {
          "key": "",
          "secret": "",
          "app_name": ""
        },
        "synchronous": true
      };
      Nimbus.Auth.setup(objAuth);
      Nimbus.Auth.authorize('GDrive');
      return Nimbus.Auth.authrized_callback = function() {
        return console.log("Authorized sucess!");
      };
    };
    $scope.shareClient = function() {
      Nimbus.Client.GDrive.add_share_user_real($scope.femail, function() {
        return console.log("add real share:" + $scope.femail);
      });
      return window.c_file.id;
    };
    appReady = function() {
      if (Nimbus.Client.GDrive.check_auth) {
        $scope.authorized = true;
        console.log("c_file.id:" + window.c_file.id);
        $scope.realtimeData = window.todo.get("text");
        Nimbus.Model.Realtime.set_objectchanged_callback(function(e) {
          console.log("changed!");
          return edit2.value = window.todo.get("text");
        });
        edit1.onkeyup = function(e) {
          return window.todo.set("text", edit1.value);
        };
        return window.startRealtime(function() {
          return $scope.isLoaded = true;
        });
      } else {
        alert("You have not authorize!");
        return $scope.authorized = false;
      }
    };
    return Nimbus.Auth.set_app_ready(appReady);
  });

  window.loadFunc = function() {
    var objAuth;
    objAuth = {
      "GDrive": {
        "key": "460727743836-sd4rpc7j65lr827sc5dokmmndhqhi48q.apps.googleusercontent.com",
        "scope": "https://www.googleapis.com/auth/drive",
        "app_name": "gdrive_realtime_test"
      },
      "Dropbox": {
        "key": "",
        "secret": "",
        "app_name": ""
      },
      "synchronous": true
    };
    Nimbus.Auth.setup(objAuth);
    Nimbus.Auth.authorize('GDrive');
    return Nimbus.Auth.authrized_callback = function() {
      return console.log("Authorized sucess!");
    };
  };

}).call(this);
