// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('Realtime', []);

  app.controller('realtimeController', function($scope) {
    var Docs, TodoModel, appReady, edit1, edit2;
    Docs = {};
    edit1 = document.getElementById('editer1');
    edit2 = document.getElementById('editer2');
    window.wTodos = TodoModel = {};
    window.debug = false;
    $scope.authorized = false;
    $scope.shared = false;
    $scope.isLoaded = false;
    $scope.Todos = [];
    $scope.Todos2 = [];
    $scope.authorize = function() {
      var objAuth;
      objAuth = {
        "GDrive": {
          "key": "460727743836-sd4rpc7j65lr827sc5dokmmndhqhi48q.apps.googleusercontent.com",
          "scope": "https://www.googleapis.com/auth/drive",
          "app_name": "gdrive_realtime_test"
        },
        "Dropbox": {
          "key": "",
          "secret": "",
          "app_name": ""
        },
        "synchronous": true
      };
      Nimbus.Auth.setup(objAuth);
      Nimbus.Auth.authorize('GDrive');
      return Nimbus.Auth.authrized_callback = function() {
        return console.log("Authorized sucess!");
      };
    };
    $scope.shareClient = function() {
      return Nimbus.Client.GDrive.add_share_user_real($scope.femail, function() {
        return console.log("add real share:" + $scope.femail);
      }, window.c_file.id);
    };
    $scope.add = function() {
      return TodoModel.create({
        "title": (new Date()).toString()
      }, function(model) {
        console.log("callback create:", model);
        return $scope.Todos.push(model);
      });
    };
    $scope.save = function(todo) {
      var t;
      t = TodoModel.find(todo.id);
      t.title = document.getElementById('editer1').value;
      return t.save(function(newRecord) {
        return console.log("callback newRecord:", newRecord);
      });
    };
    appReady = function() {
      if (Nimbus.Auth.authorized) {
        window.wTodoModel = TodoModel = Nimbus.Model.setup("Todos", ["title"]);
        return TodoModel.sync_all(function() {
          var t, _i, _len, _ref;
          _ref = TodoModel.all();
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            t = _ref[_i];
            $scope.Todos.push(t);
          }
          TodoModel.set_objectchanged_callback(function(currentEvent, Obj, serverevent) {
            console.log("currentEvent:" + currentEvent);
            console.log("Obj:" + Obj);
            console.log("serverevent:" + serverevent);
            return document.getElementById('editer2').value = Obj;
          });
          window.startRealtime(function() {
            return console.log("RealTimeStart!");
          });
          return $scope.$apply();
        });
      } else {
        alert("You have not authorize!");
        return $scope.authorized = false;
      }
    };
    return Nimbus.Auth.set_app_ready(appReady);
  });

  window.loadFunc = function() {
    var objAuth;
    objAuth = {
      "GDrive": {
        "key": "460727743836-sd4rpc7j65lr827sc5dokmmndhqhi48q.apps.googleusercontent.com",
        "scope": "https://www.googleapis.com/auth/drive",
        "app_name": "gdrive_realtime_test"
      },
      "Dropbox": {
        "key": "",
        "secret": "",
        "app_name": ""
      },
      "synchronous": true
    };
    return Nimbus.Auth.setup(objAuth);
  };

}).call(this);
